# Generated by Django 5.2.5 on 2026-02-02 16:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("opportunities", "0002_application"),
        ("youth_profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_viewed", models.BooleanField(default=False)),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="opportunities.opportunity",
                    ),
                ),
                (
                    "youth_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="youth_profiles.youthprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-overall_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage of required skills matched",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "location_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Location proximity score",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "experience_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Experience level compatibility",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "skill_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.5,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "location_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.3,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "experience_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.2,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "matched_skills",
                    models.JSONField(
                        default=list, help_text="List of skills that matched"
                    ),
                ),
                (
                    "missing_skills",
                    models.JSONField(
                        default=list, help_text="Required skills the youth doesn't have"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_breakdown",
                        to="matching.match",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match Score Breakdown",
                "verbose_name_plural": "Match Score Breakdowns",
            },
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["-overall_score"], name="matching_ma_overall_fbaa43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["youth_profile", "-overall_score"],
                name="matching_ma_youth_p_a7388d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="match",
            unique_together={("youth_profile", "opportunity")},
        ),
    ]
