# Generated by Django 5.2.5 on 2025-10-10 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("company_description", models.TextField(blank=True)),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("tech", "Technology"),
                            ("finance", "Finance"),
                            ("education", "Education"),
                            ("healthcare", "Healthcare"),
                            ("retail", "Retail"),
                            ("manufacturing", "Manufacturing"),
                            ("agriculture", "Agriculture"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=100,
                    ),
                ),
                ("company_website", models.URLField(blank=True)),
                ("company_email", models.EmailField(blank=True, max_length=254)),
                ("company_phone", models.CharField(blank=True, max_length=15)),
                ("county", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("address", models.TextField(blank=True)),
                ("verified", models.BooleanField(default=False)),
                (
                    "verification_document",
                    models.FileField(blank=True, null=True, upload_to="employer_docs/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "employer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
