# Generated by Django 5.2.5 on 2025-10-16 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Technology", "Technology"),
                            ("Agriculture", "Agriculture"),
                            ("Healthcare", "Healthcare"),
                            ("Education", "Education"),
                            ("Construction", "Construction"),
                            ("Hospitality", "Hospitality"),
                            ("Finance", "Finance"),
                            ("Marketing", "Marketing"),
                            ("Sales", "Sales"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "opportunity_type",
                    models.CharField(
                        choices=[
                            ("Full-time", "Full-time"),
                            ("Part-time", "Part-time"),
                            ("Contract", "Contract"),
                            ("Internship", "Internship"),
                            ("Freelance", "Freelance"),
                            ("Gig", "Gig"),
                        ],
                        max_length=50,
                    ),
                ),
                ("county", models.CharField(max_length=100)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "experience_required",
                    models.CharField(
                        choices=[
                            ("Entry Level", "Entry Level"),
                            ("1-2 years", "1-2 years"),
                            ("3-5 years", "3-5 years"),
                            ("5+ years", "5+ years"),
                        ],
                        default="Entry Level",
                        max_length=50,
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum salary in KES",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum salary in KES",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("application_deadline", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="employers.employerprofile",
                    ),
                ),
                (
                    "required_skills",
                    models.ManyToManyField(
                        blank=True,
                        related_name="opportunities",
                        to="opportunities.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
