from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from youth_profiles.models import YouthProfile
from opportunities.models import Opportunity


class Match(models.Model):
    """
    Represents a match between a youth profile and an opportunity.
    Generated by the matching algorithm.
    """

    youth_profile = models.ForeignKey(
        YouthProfile, on_delete=models.CASCADE, related_name="matches"
    )
    opportunity = models.ForeignKey(
        Opportunity, on_delete=models.CASCADE, related_name="matches"
    )

    # Overall match score (0-100)
    overall_score = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        validators=[MinValueValidator(0), MaxValueValidator(100)],
    )

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Track if youth has viewed this match
    is_viewed = models.BooleanField(default=False)
    viewed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["-overall_score", "-created_at"]
        unique_together = ["youth_profile", "opportunity"]
        indexes = [
            models.Index(fields=["-overall_score"]),
            models.Index(fields=["youth_profile", "-overall_score"]),
        ]

    def __str__(self):
        return f"Match: {self.youth_profile.user.username} → {self.opportunity.title} ({self.overall_score}%)"


class MatchScore(models.Model):
    """
    Detailed breakdown of match scoring components.
    Stores individual scores for skills, location, and experience.
    """

    match = models.OneToOneField(
        Match, on_delete=models.CASCADE, related_name="score_breakdown"
    )

    # Individual score components (0-100 each)
    skill_score = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        help_text="Percentage of required skills matched",
    )

    location_score = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        help_text="Location proximity score",
    )

    experience_score = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        help_text="Experience level compatibility",
    )

    # Weights used in calculation (should sum to 1.0)
    skill_weight = models.DecimalField(
        max_digits=3,
        decimal_places=2,
        default=0.50,  # 50% weight to skills
        validators=[MinValueValidator(0), MaxValueValidator(1)],
    )

    location_weight = models.DecimalField(
        max_digits=3,
        decimal_places=2,
        default=0.30,  # 30% weight to location
        validators=[MinValueValidator(0), MaxValueValidator(1)],
    )

    experience_weight = models.DecimalField(
        max_digits=3,
        decimal_places=2,
        default=0.20,  # 20% weight to experience
        validators=[MinValueValidator(0), MaxValueValidator(1)],
    )

    # Additional metadata
    matched_skills = models.JSONField(
        default=list, help_text="List of skills that matched"
    )
    missing_skills = models.JSONField(
        default=list, help_text="Required skills the youth doesn't have"
    )

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Match Score Breakdown"
        verbose_name_plural = "Match Score Breakdowns"

    def __str__(self):
        return f"Score for {self.match}"
